/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './hero.service';
import * as import4 from './heroes.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/common/src/directives/ng_for';
import * as import11 from './hero-detail.component';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import14 from './hero-detail.component.ngfactory';
import * as import15 from '@angular/core/src/metadata/view';
var renderType_HeroesComponent_Host:import0.RenderComponentType = null;
class _View_HeroesComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  private _appEl_0:import2.AppElement;
  _HeroService_0_4:import3.HeroService;
  _HeroesComponent_0_5:import4.HeroesComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroesComponent_Host0,renderType_HeroesComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-heroes',rootSelector,null);
    this._appEl_0 = new import2.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_HeroesComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeroService_0_4 = new import3.HeroService();
    this._HeroesComponent_0_5 = new import4.HeroesComponent(this._HeroService_0_4);
    this._appEl_0.initComponent(this._HeroesComponent_0_5,[],compView_0);
    compView_0.create(this._HeroesComponent_0_5,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeroService) && (0 === requestNodeIndex))) { return this._HeroService_0_4; }
    if (((token === import4.HeroesComponent) && (0 === requestNodeIndex))) { return this._HeroesComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeroesComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeroesComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeroesComponent_Host === null)) { (renderType_HeroesComponent_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_HeroesComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeroesComponentNgFactory:import9.ComponentFactory<import4.HeroesComponent> = new import9.ComponentFactory<import4.HeroesComponent>('my-heroes',viewFactory_HeroesComponent_Host0,import4.HeroesComponent);
const styles_HeroesComponent:any[] = ['.selected[_ngcontent-%COMP%] {\n      background-color: #CFD8DC !important;\n      color: white;\n    }\n    .heroes[_ngcontent-%COMP%] {\n      margin: 0 0 2em 0;\n      list-style-type: none;\n      padding: 0;\n      width: 15em;\n    }\n    .heroes[_ngcontent-%COMP%] li[_ngcontent-%COMP%] {\n      cursor: pointer;\n      position: relative;\n      left: 0;\n      background-color: #EEE;\n      margin: .5em;\n      padding: .3em 0;\n      height: 1.6em;\n      border-radius: 4px;\n    }\n    .heroes[_ngcontent-%COMP%] li.selected[_ngcontent-%COMP%]:hover {\n      background-color: #BBD8DC !important;\n      color: white;\n    }\n    .heroes[_ngcontent-%COMP%] li[_ngcontent-%COMP%]:hover {\n      color: #607D8B;\n      background-color: #DDD;\n      left: .1em;\n    }\n    .heroes[_ngcontent-%COMP%] .text[_ngcontent-%COMP%] {\n      position: relative;\n      top: -3px;\n    }\n    .heroes[_ngcontent-%COMP%] .badge[_ngcontent-%COMP%] {\n      display: inline-block;\n      font-size: small;\n      color: white;\n      padding: 0.8em 0.7em 0 0.7em;\n      background-color: #607D8B;\n      line-height: 1em;\n      position: relative;\n      left: -1px;\n      top: -4px;\n      height: 1.8em;\n      margin-right: .8em;\n      border-radius: 4px 0 0 4px;\n    }'];
var renderType_HeroesComponent:import0.RenderComponentType = null;
class _View_HeroesComponent0 extends import1.AppView<import4.HeroesComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _anchor_6:any;
  private _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgFor_6_6:import10.NgFor;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  private _appEl_9:import2.AppElement;
  _HeroDetailComponent_9_4:import11.HeroDetailComponent;
  _text_10:any;
  private _expr_0:any;
  private _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroesComponent0,renderType_HeroesComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',null);
    this._el_1 = this.renderer.createElement(parentRenderNode,'h2',null);
    this._text_2 = this.renderer.createText(this._el_1,'My Heroes',null);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',null);
    this._el_4 = this.renderer.createElement(parentRenderNode,'ul',null);
    this.renderer.setElementAttribute(this._el_4,'class','heroes');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',null);
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,null);
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import12.TemplateRef_(this._appEl_6,viewFactory_HeroesComponent1);
    this._NgFor_6_6 = new import10.NgFor(this._appEl_6.vcRef,this._TemplateRef_6_5,this.parentInjector.get(import13.IterableDiffers),this.ref);
    this._text_7 = this.renderer.createText(this._el_4,'\n    ',null);
    this._text_8 = this.renderer.createText(parentRenderNode,'\n    ',null);
    this._el_9 = this.renderer.createElement(parentRenderNode,'my-hero-detail',null);
    this._appEl_9 = new import2.AppElement(9,null,this,this._el_9);
    var compView_9:any = import14.viewFactory_HeroDetailComponent0(this.viewUtils,this.injector(9),this._appEl_9);
    this._HeroDetailComponent_9_4 = new import11.HeroDetailComponent();
    this._appEl_9.initComponent(this._HeroDetailComponent_9_4,[],compView_9);
    compView_9.create(this._HeroDetailComponent_9_4,[],null);
    this._text_10 = this.renderer.createText(parentRenderNode,'\n  ',null);
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import10.NgFor) && (6 === requestNodeIndex))) { return this._NgFor_6_6; }
    if (((token === import11.HeroDetailComponent) && (9 === requestNodeIndex))) { return this._HeroDetailComponent_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.heroes;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_6_6.ngForOf = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (!throwOnChange) { this._NgFor_6_6.ngDoCheck(); }
    const currVal_1:any = this.context.selectedHero;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._HeroDetailComponent_9_4.hero = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_HeroesComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.HeroesComponent> {
  if ((renderType_HeroesComponent === null)) { (renderType_HeroesComponent = viewUtils.createRenderComponentType('/Users/laco/Works/ng2-compiler-test2/src/heroes.component.ts class HeroesComponent - inline template',0,import15.ViewEncapsulation.Emulated,styles_HeroesComponent,{})); }
  return new _View_HeroesComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeroesComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  private _expr_1:any;
  private _expr_2:any;
  private _expr_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroesComponent1,renderType_HeroesComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement(null,'li',null);
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',null);
    this._el_2 = this.renderer.createElement(this._el_0,'span',null);
    this.renderer.setElementAttribute(this._el_2,'class','badge');
    this._text_3 = this.renderer.createText(this._el_2,'',null);
    this._text_4 = this.renderer.createText(this._el_0,'',null);
    this._expr_1 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return null;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = (this.context.$implicit === this.parent.context.selectedHero);
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'selected',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import5.interpolate(1,'',this.context.$implicit.id,'');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_3,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import5.interpolate(1,' ',this.context.$implicit.name,'\n      ');
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_4,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onSelect(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeroesComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeroesComponent1(viewUtils,parentInjector,declarationEl);
}